services:
  db:
    image: mariadb:latest
    command: '--default-authentication-plugin=mysql_native_password'
    restart: always
    volumes:
      - db_data:/var/lib/mysql
    expose:
      - 3306
      - 33060
    environment:
      MYSQL_ROOT_PASSWORD: your_db_root_password
      MYSQL_DATABASE: your_db_name
      MYSQL_USER: your_db_user
      MYSQL_PASSWORD: your_db_user_password

  wordpress:
    image: wordpress:latest
    restart: always
    ports:
      - 8080:80
    volumes:
      - wordpress_data:/var/www/html
    depends_on:
      - db
    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_USER: your_db_user
      WORDPRESS_DB_PASSWORD: your_db_user_password
      WORDPRESS_DB_NAME: your_db_name

volumes:
  db_data:
  wordpress_data:  
